### ISSUE TITLE
Clicking "Check all" twice will set the "default" dataset to Witvliet instead of Randi

### ISSUE THREAD

**Issue by lparsons** [PrincetonUniversity/neuron-graph#101]
**Problem**

Clicking the "Check all" button for datasets will first select all the datasets. Clicking it a second time will reset the selected datasets to some "default", which right now is Witvliet 2020, however, it should be Randi 2022.

**Steps to reproduce**

1. Go to https://funconn.princeton.edu
2. Open the left setting menu
3. Select the "Head ganglia" dataset group
4. Click on the "Check all" button to select all available datasets
5. Click on the "Check all" button again to deselect all datasets and select only a "default" set

**Current behavior**

The Witvliet 2020 dataset it selected by default.

**Expected behavior**

The Randi 2022 dataset should be selected by default.

**Suggested Change**

A guess at what might fix the issue.  *Pseudocode encouraged.*

**Comment**

![image](https://user-images.githubusercontent.com/645128/181598879-8792e830-c177-422c-959c-4bb0e0bee5c3.png)
![image](https://user-images.githubusercontent.com/645128/181598904-d6864a9c-e413-4411-bd90-9c8871b01851.png)

**Comment by hepcat72** [comment]
@lparsons @bdsinger I looked at this a bit before Zoe told me about a water leak in the basement and ran off downstairs. It appears that when you un-check check-all, it default-selects the *last* dataset in each category (head, tail, complete, and unc31). I'm not 100% certain where the order is determined (static from the json or based on the time setting), but following that code was pretty circuitous. I would try changing the json and re-populating the DB first (because there is a white dataset that appears after witvliet - though that's "visual time") and if that doesn't work, change the time of the randi set to be last.

Or... we could overhaul the code to actually remember the previous selection... ;)

**Comment by bdsinger** [comment]
I reframed this as a bug where it will not uncheck all datasets despite what the button says. Now it will. If you want to select one after doing that, you can. And status of selections is already saved as a cookie, as you can see by what is selected next time you use it.
